// Generated by CoffeeScript 1.6.2
var app, db, env, logging, _ref;

_ref = require('../../require_tree').require_tree('./test/config', {
  preserve_filenames: true
}), app = _ref.app, db = _ref.db, logging = _ref.logging;
// console.log(module.parent.exports);
module.parent.exports.extendTree( {
  config: {
    env: env = process.env.NODE_ENV || app.env,
    port: app.port[env],
    db: db[env],
    logging: logging[env]
  }
});

// (function(global) {
	// var app, db, env, logging, _ref;
// 	
	// _ref = module.parent.exports.require_tree('./test/config', {
	  // preserve_filenames: true
	// }), app = _ref.app, db = _ref.db, logging = _ref.logging;
// 	
// 	
	// return global.config = {};
// })(exports);
